version: '3'

services:
  # nestjs_api:
  #   container_name: nestjs_api
  #   build:
  #     context: .
  #   ports:
  #     - 4200:4200
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app 
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes: 
      - postgres_db:/var/lib/postgresql/data

networks:
  app:
    driver: bridge

volumes:
  postgres_db: